name: Build
on:
  workflow_dispatch:
jobs:
  Build:
    name: Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Build
        run: |
          git clone https://github.com/GunGunGun/HeaderEditor.git
          cd HeaderEditor/
          #npm i -g pnpm
          #wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm
          pnpm i
          npm run build
          zip -r headereditor.zip ./dist
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ./headereditor.zip
          name: Addon
          tag_name: all
          body: Download Here
